# Generated by Django 3.2.4 on 2021-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_sal', models.FloatField()),
                ('emp_address', models.CharField(max_length=20)),
            ],
        ),
    ]
